# Site settings
title: Advon Analytics
email: contact@advonanalytics.com
description: > # this means to ignore newlines until "baseurl:"
 Creative is a one page Bootstrap theme for creatives, small businesses, and other multipurpose uses.
 The theme includes a number of rich features and plugins that you can use as a great boilerplate for your next Jekyll project!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://advonanalytics.com" # the base hostname & protocol for your site

#twitter_username: volnyio
#github_username:  volny

# Build settings
markdown: kramdown
